/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DatosDeber;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bryan
 */
public class DatosPanel extends javax.swing.JFrame {

    ArrayList<Materias> listaMaterias = new ArrayList();
    DefaultTableModel modeloTablaMaterias ;
    String[][] materias;
    DefaultComboBoxModel modeloComboBoxMaterias = new DefaultComboBoxModel();
    
    
    
    
    
    public DatosPanel() {
        initComponents();
        
        String[] titulosTablaMaterias = new String[]{"Materias"};
        modeloTablaMaterias = new DefaultTableModel(materias,titulosTablaMaterias);
        tableMateria.setModel(modeloTablaMaterias);
        
        comboMateriasProfesores.setModel(modeloComboBoxMaterias);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pestaña4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        labelIngresarMateria = new javax.swing.JLabel();
        textMateria = new javax.swing.JTextField();
        buttonIngresarMateria = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMateria = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        labelNombreProfesor = new javax.swing.JLabel();
        labelApellidoProfesor = new javax.swing.JLabel();
        labelFacultadProfesor = new javax.swing.JLabel();
        labelMateriaProfesor = new javax.swing.JLabel();
        buttonAgregarProfesor = new javax.swing.JButton();
        textNombreProfesor = new javax.swing.JTextField();
        textApellidoProfesor = new javax.swing.JTextField();
        textFacultadProfesor = new javax.swing.JTextField();
        comboMateriasProfesores = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        labelNombreEstudiante = new javax.swing.JLabel();
        labelApellidoEstudiante = new javax.swing.JLabel();
        labelCarreraEstudiante = new javax.swing.JLabel();
        textNombreEstudiante = new javax.swing.JTextField();
        textApellidoEstudiante = new javax.swing.JTextField();
        comboCarrerasEstudiantes = new javax.swing.JComboBox<>();
        buttonRegistrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEstudiante = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        labelEstudianteMatriculado = new javax.swing.JLabel();
        labelMateriaMatriculada = new javax.swing.JLabel();
        comboEstudianteMatricula = new javax.swing.JComboBox<>();
        comboMateriaMatricula = new javax.swing.JComboBox<>();
        buttonMatricula = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableMatricula = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelIngresarMateria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelIngresarMateria.setText("Ingrese una nueva materia:");

        buttonIngresarMateria.setText("Ingresar");
        buttonIngresarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIngresarMateriaActionPerformed(evt);
            }
        });

        tableMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableMateria);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(buttonIngresarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelIngresarMateria)
                                .addGap(34, 34, 34)
                                .addComponent(textMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIngresarMateria)
                    .addComponent(textMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(buttonIngresarMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        Pestaña4.addTab("Materia ", jPanel1);

        labelNombreProfesor.setText("Nombre:");

        labelApellidoProfesor.setText("Apellido:");

        labelFacultadProfesor.setText("Facultad:");

        labelMateriaProfesor.setText("Materia:");

        buttonAgregarProfesor.setText("Agregar");

        comboMateriasProfesores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonAgregarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(labelMateriaProfesor)
                                    .addGap(75, 75, 75)
                                    .addComponent(comboMateriasProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelApellidoProfesor)
                                        .addComponent(labelNombreProfesor))
                                    .addGap(75, 75, 75)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textNombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textApellidoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelFacultadProfesor)
                                .addGap(75, 75, 75)
                                .addComponent(textFacultadProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(130, 130, 130))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreProfesor)
                    .addComponent(textNombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellidoProfesor)
                    .addComponent(textApellidoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFacultadProfesor)
                    .addComponent(textFacultadProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMateriaProfesor)
                    .addComponent(comboMateriasProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(buttonAgregarProfesor)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        Pestaña4.addTab("Profesor", jPanel2);

        labelNombreEstudiante.setText("Nombre:");

        labelApellidoEstudiante.setText("Apellido:");

        labelCarreraEstudiante.setText("Carrera:");

        comboCarrerasEstudiantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonRegistrar.setText("Registrar");

        tableEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableEstudiante);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCarreraEstudiante)
                            .addComponent(labelApellidoEstudiante)
                            .addComponent(labelNombreEstudiante))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textApellidoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCarrerasEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(buttonRegistrar)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombreEstudiante))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textApellidoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelApellidoEstudiante)
                    .addComponent(buttonRegistrar))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCarreraEstudiante)
                    .addComponent(comboCarrerasEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Pestaña4.addTab("Estudiante", jPanel3);

        labelEstudianteMatriculado.setText("Estudiante:");

        labelMateriaMatriculada.setText("Materia:");

        comboEstudianteMatricula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboMateriaMatricula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonMatricula.setText("Aceptar");

        tableMatricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tableMatricula);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEstudianteMatriculado)
                    .addComponent(labelMateriaMatriculada))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboEstudianteMatricula, 0, 100, Short.MAX_VALUE)
                    .addComponent(comboMateriaMatricula, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMatricula))
                .addGap(44, 44, 44))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstudianteMatriculado)
                    .addComponent(comboEstudianteMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(buttonMatricula)
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMateriaMatriculada)
                    .addComponent(comboMateriaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        Pestaña4.addTab("Matricula", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Pestaña4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pestaña4)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIngresarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIngresarMateriaActionPerformed
        // TODO add your handling code here:
        String materia = textMateria.getText();
        boolean exist = false;
        
        //para comparar con un if normal
        String[] materiaIngresada = new String[]{materia};
        //esto lleva al constructor para comparar las materias 
        //primero necesito instanciar para poder comparar
        Materias materiasRegistradas = new Materias(materia);
        //---> listaMaterias.add(materiasRegistradas); esto no va poruqe ya pongo la condicional
        //de mi objeto Materias que me compare cada item de mi listaMaterias
        for( Materias item: listaMaterias){
            
            if(item.getNombre().equals(materiasRegistradas.getNombre() ) ){
                
                int iconoAviso = JOptionPane.WARNING_MESSAGE;
                JOptionPane.showMessageDialog(rootPane, "NOTA", "Esta materia ya fue registrada", iconoAviso);
                
                exist = true;
                break;
        }
        }
            
         if(exist == false){
             
             listaMaterias.add(materiasRegistradas);
             modeloTablaMaterias.addRow(materiaIngresada);
             modeloComboBoxMaterias.addElement(materiasRegistradas);
             
           
         }   
           
        
        
       
    }//GEN-LAST:event_buttonIngresarMateriaActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Pestaña4;
    private javax.swing.JButton buttonAgregarProfesor;
    private javax.swing.JButton buttonIngresarMateria;
    private javax.swing.JButton buttonMatricula;
    private javax.swing.JButton buttonRegistrar;
    private javax.swing.JComboBox<String> comboCarrerasEstudiantes;
    private javax.swing.JComboBox<String> comboEstudianteMatricula;
    private javax.swing.JComboBox<String> comboMateriaMatricula;
    private javax.swing.JComboBox<String> comboMateriasProfesores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelApellidoEstudiante;
    private javax.swing.JLabel labelApellidoProfesor;
    private javax.swing.JLabel labelCarreraEstudiante;
    private javax.swing.JLabel labelEstudianteMatriculado;
    private javax.swing.JLabel labelFacultadProfesor;
    private javax.swing.JLabel labelIngresarMateria;
    private javax.swing.JLabel labelMateriaMatriculada;
    private javax.swing.JLabel labelMateriaProfesor;
    private javax.swing.JLabel labelNombreEstudiante;
    private javax.swing.JLabel labelNombreProfesor;
    private javax.swing.JTable tableEstudiante;
    private javax.swing.JTable tableMateria;
    private javax.swing.JTable tableMatricula;
    private javax.swing.JTextField textApellidoEstudiante;
    private javax.swing.JTextField textApellidoProfesor;
    private javax.swing.JTextField textFacultadProfesor;
    private javax.swing.JTextField textMateria;
    private javax.swing.JTextField textNombreEstudiante;
    private javax.swing.JTextField textNombreProfesor;
    // End of variables declaration//GEN-END:variables
}
